version: "3.8"
services:
  redis:
    restart: always
    image: "redis:alpine"
    container_name: redis
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
    ports:
      - 6379:6379
  overtimemarkets-bot:
    restart: always
    image: thalesmarket/overtimecreator
    #image: thalesmarket/overtimeodds
    #image: thalesmarket/overtimeresolver
    environment:
      - "PRIVATE_KEY=''"
      - "WALLET=''"
      - "REQUEST_KEY=''"
      - "INFURA=XXXXX"
      - "INFURA_URL=https://optimism-mainnet.infura.io/v3/XXXXXX"
      - "NETWORK=optimism"
      - "NETWORK_ID=10"
      - "BASE_URL=https://api.0x.org/sra/v4/"
      - "RUNDOWN_BASE_URL=https://therundown-therundown-v1.p.rapidapi.com"
      - "GAME_QUEUE_CONTRACT=0x5417c847b6ce4163C43116E8D9670395Ba08B503"
      - "WRAPPER_CONTRACT=0xe7f379DCaD66A5128f44a996D276Cf55E6D8F2c5"
      - "CONSUMER_CONTRACT=0x2B91c14Ce9aa828eD124D12541452a017d8a2148"
      - "LINK_CONTRACT=0x350a791bfc2c21f9ed5d10980dad2e2638ffa7f6"
      - "MILISECONDS=1000"
      - "CREATION_DAYS_INFRONT=7"
      - "JOB_ID_CREATION=5cc84835a9964b2da72787789950807e"
      - "MARKET_CREATION=create"
      - "SPORT_IDS=2,3,7,10,11,12,13,14,15"
      - "MARKET_RESOLVE=resolve"
      - "JOB_ID_RESOLVE=5cc84835a9964b2da72787789950807e"
      - "EXPECTED_GAME_MLB=10800"
      - "EXPECTED_GAME_FOOTBAL=7200"
      - "EXPECTED_GAME_UFC=12600"
      - "EXPECTED_GAME_NFL=12600"
      - "JOB_ID_ODDS=d4f5cebf842d4063a9743ad32e694c4f"
      - "ODDS_PERCENRAGE_CHANGE=2"
      - "CREATION_FREQUENCY=43200000"
      - "RESOLVE_FREQUENCY=900000"
      - "ODDS_FREQUENCY=600000"
      - "CREATE_BATCH=10"
      - "RESOLVE_BATCH=10"
      - "RESOLVE_STATUSES=STATUS_FINAL,STATUS_FULL_TIME"
      - "CANCEL_STATUSES=STATUS_CANCELED,STATUS_POSTPONED,STATUS_ABANDONED"
      - "ODDS_PERCENTAGE_CHANGE_MLB=1"
      - "ODDS_PERCENTAGE_CHANGE_MLS=1"
      - "ODDS_PERCENTAGE_CHANGE_UFC=1"
      - "ODDS_PERCENTAGE_CHANGE_DEFAULT=2"
      - "BOT_OVERTIME_ODDS=''"
      - "BOT_OVERTIME_CREATOR=''"
      - "BOT_OVERTIME_RESOLVER=''"
      - "LINK_THRESHOLD=5000000000000000000"
      - "USE_BACKUP_ODDS_BOOKMAKER=true"
      - "PRIMARY_ODDS_BOOKMAKER=3"
      - "BACKUP_ODDS_BOOKMAKER=11"
      - "RESOLVE_DAYS_INBACK=1"
      - "CL_RESOLVE_BATCH=5"

volumes:
  redis-data:
