version: "3.8"
services:
  redis:
    restart: always
    image: "redis:alpine"
    container_name: redis
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
    ports:
      - 6379:6379
  overtimemarkets-bot:
    restart: always
    image: thalesmarket/overtimecreator
    #image: thalesmarket/overtimeodds
    #image: thalesmarket/overtimeresolver
    environment:
      - "PRIVATE_KEY=''"
      - "WALLET=''"
      - "REQUEST_KEY=''"
      - "INFURA=16f15a8ff9f54b2394086bda0b237611"
      - "INFURA_URL=https://optimism-mainnet.infura.io/v3/16f15a8ff9f54b2394086bda0b237611"
      - "NETWORK=optimism"
      - "NETWORK_ID=10"
      - "BASE_URL=https://api.0x.org/sra/v4/"
      - "RUNDOWN_BASE_URL=https://therundown-therundown-v1.p.rapidapi.com"
      - "GAME_QUEUE_CONTRACT=0x5417c847b6ce4163C43116E8D9670395Ba08B503"
      - "WRAPPER_CONTRACT=0x1687fDC8A409Be442e2dD3DE42b1fcC974Ac9eE8"
      - "CONSUMER_CONTRACT=0x2B91c14Ce9aa828eD124D12541452a017d8a2148"
      - "LINK_CONTRACT=0x350a791bfc2c21f9ed5d10980dad2e2638ffa7f6"
      - "MILISECONDS=1000"
      - "CREATION_DAYS_INFRONT=7"
      - "JOB_ID_CREATION=5cc84835a9964b2da72787789950807e"
      - "MARKET_CREATION=create"
      - "SPORT_IDS=3,10"
      - "MARKET_RESOLVE=resolve"
      - "JOB_ID_RESOLVE=5cc84835a9964b2da72787789950807e"
      - "EXPECTED_GAME_DURATIN=7200"
      - "JOB_ID_ODDS=d4f5cebf842d4063a9743ad32e694c4f"
      - "ODDS_PERCENRAGE_CHANGE=2"
      - "CREATION_FREQUENCY=86400000"
      - "RESOLVE_FREQUENCY=900000"
      - "ODDS_FREQUENCY=600000"
      - "CREATE_BATCH=10"
      - "RESOLVE_BATCH=10"
volumes:
  redis-data:
